### ISSUE TITLE
[BUG] Moved item is not searchable.

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-client#877] opened 2020-09-11 08:57 UTC
# 🐜 Bug Report

I moved a file successfully. The file is browseable (I can see in the tree), but I cannot find it by the filename extension.

## 👉 Steps To Reproduce

- Login
- Navigate to Content
- Create a DocumentLibrary: "MyDocs"
- Upload two excels into the "MyDocs" e.g. "1.xlsx", "2.xlsx"
- Go to Content
- Upload here the "3.xlsx"
- Move the "3.xlsx" into the "MyDocs"
- Click the "Search" icon on the head.
- Type "*.xlsx" + <ENTER>
- Check the result list.

## 😯 Current behavior

The "3.xlsx" is missing.

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device:
  
- OS:
  
- Browser:
  
- Version:

**Comment by pusztaienike** [comment] 2020-09-15 14:30
Cannot reproduce:
![image](https://user-images.githubusercontent.com/22347393/93223788-b7301180-f770-11ea-9ce2-c81adfee8cea.png)

**Comment by herflis** [comment] 2020-09-30 07:02
@kavics We cannot reproduce this issue. Can you please check this again and if you cannot reproduce it either we could close this issue

**Closed** 2020-10-05 08:05 UTC
Labels: bug, snaas
