### ISSUE TITLE
[E2E test] Add Cypress test - Setup menu

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sn-client#794] opened 2020-08-18 15:25 UTC
**_Before you start working on an issue please take a look  at our [dedicated hacktoberfest site](https://hacktoberfest.sensenet.com/#eventDetails) to learn the basic rules and find additional resources to help you get started._**

# 🧪E2E test cases

The scope of these tests is to ensure that the Setup menu works as it is intended.

![image](https://user-images.githubusercontent.com/22347393/90529810-68dd2200-e174-11ea-9cd3-fa3ba4783aa0.png)

## 😎 Role

All test should run as admin.

# Test case 1

## 🧫 Purpose of the test

Right click on a "settings item" should make context-menu open.

## 🐾 Steps

1. Login with admin role
2. Click on 'Setup' menuitem
3. **Step:** Right click on DocumentPreview.settings item
    **Expected result:** The context-menu dropdown should be visible with the following actions:

- Browse
- Copy to
- Edit
- Move to
- Check out
- Download

4. Click away

# Test case 2

## 🧫 Purpose of the test

Click on Edit button should open a binary editor with the content of the 'settings item'.

## 🐾 Steps

1. **Step:** Click on Edit button of DocumentPreview.settings item
    **Expected result:** A binary editor has appears with the content of DocumentPreview.settings on a new page. The page should contain the name of the 'settings item' (DocumentPreview.settings)
2. Click on Cancel button

# Test case 3

## 🧫 Purpose of the test

Click on 'Learn more' button should open the document of the selected 'settings item'.

## 🐾 Steps

1. **Step:** Click on 'Learn more' button of DocumentPreview.settings item
    **Expected result:** The document of DocumentPreview.settings should open (link: https://community.sensenet.com/docs/admin-ui/setup/#documentpreview-settings)

**Comment by mitcom** [comment] 2020-10-12 12:51
I tried to "semi manually" (manually but in Cypress app) preview those test cases and I have some differences in the very beginning.
Test case 1, expected behaviour:
- Browse
- Copy to
- Edit
- Move to
- Versions
- Check out
- Share (disabled)
- Delete
- Set permissions
- Download

I have 
![Screenshot from 2020-10-12 14-41-20](https://user-images.githubusercontent.com/1809192/95748414-3e05da80-0c9a-11eb-9131-0e4a9fda3488.png)

I thought about the permissions mismatch, but I should be logged in as `admin` as I assume `cy.login()` does

**Comment by herflis** [comment] 2020-10-12 12:59
> I tried to "semi manually" (manually but in Cypress app) preview those test cases and I have some differences in the very beginning.
> Test case 1, expected behaviour:
> 
> * Browse
> * Copy to
> * Edit
> * Move to
> * Versions
> * Check out
> * Share (disabled)
> * Delete
> * Set permissions
> * Download
> 
> I have
> ![Screenshot from 2020-10-12 14-41-20](https://user-images.githubusercontent.com/1809192/95748414-3e05da80-0c9a-11eb-9131-0e4a9fda3488.png)
> 
> I thought about the permissions mismatch, but I should be logged in as `admin` as I assume `cy.login()` does

thank you @mitcom for reporting this! 💙 Yes, you're right, it seems that the menuitems was changed since the test case is written. I'm updating the issue.

**Comment by milantenk** [comment] 2020-10-17 17:28
I would like to work on this issue, could you please assign it to me?

**Comment by herflis** [comment] 2020-10-17 17:32
Hi @milantenk it is assigned to you now. Let us know if we can help you with anything

**Comment by milantenk** [comment] 2020-10-20 18:55
Should I add `data-test` attribute where it is necessary or should I use CSS classes / XPaths in those cases where a `data-test` attribute would be handy?

**Comment by pusztaienike** [comment] 2020-10-20 19:00
> Should I add `data-test` attribute where it is necessary or should I use CSS classes / XPaths in those cases where a `data-test` attribute would be handy?

Dear milantenk, 
We prefer `data-test` attributes, you can add them where you need it :) Good luck!

**Comment by milantenk** [comment] 2020-10-21 05:41
Okok, thank you for the quick reaction! :)

**Closed** 2020-10-27 16:49 UTC
Labels: cypress, good first issue, hacktoberfest, help wanted, test
