### ISSUE TITLE
[BUG][admin-ui] Deleting current content breaks the ui

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#389] opened 2019-09-13 09:15 UTC
# 🐜 Bug Report

When the user deletes the current content/parent from the tree the list cannot load the children and breaks with the error message 'Somethin went wrong'

## 📦 Package / Application

@sensenet/sn-app

## 📃 Version

1.0.0

## 👉 Steps To Reproduce

1. Go to admin-ui and login with admin
2. Open /Content from the drawer menu
3. Open a container and lists its children with choosing it from the tree
4. Open the parent items actionmenu with right-clicking on it
5. Click on delete, select to delete the item permanently and hit the delete button
6. The content is deleted but there's an error message dialog showing with the message 'something went wrong'

## 😯 Current behavior

The current context/parent remains the same after the content is deleted and the list cannot load its children.

## 🤔 Expected behavior

1. If it is possible in this cases the current parent should be replaced with the deleted items parent
2. If the first solution cannot be made, then the delete action should not be displayed in the actionmenu in the tree.

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/6968860/64851382-8fffab00-d617-11e9-92c4-21745ea02c8b.png)

![image](https://user-images.githubusercontent.com/6968860/64851397-9a21a980-d617-11e9-9065-cb5013d53d66.png)

![image](https://user-images.githubusercontent.com/6968860/64851439-a9a0f280-d617-11e9-8e15-9f31ecf654c0.png)

**Comment by pradeepmurugesan** [comment] 2019-10-05 18:52
I can work on this..

**Comment by pradeepmurugesan** [comment] 2019-10-06 14:07
@herflis I have a mac. Is it possible to set up a dev env using .Net core or is should I definitely need windows ?

**Comment by herflis** [comment] 2019-10-07 14:01
Hi @pradeepmurugesan you don't have to install sensenet, use simply our [dev demo site](https://dev.demo.sensenet.com) as the repository.
Fork  the [sn-client](https://github.com/SenseNet/sn-client) the admin-uis source code is here and you can build the admin-ui locally.
You can login with name: BuiltIn\admin, password: admin and https://dev.demo.sensenet.com as repository url

**Comment by pradeepmurugesan** [comment] 2019-10-07 14:32
@herflis Great.. Thanks.. Will try the same and let you know if I face any issues.. 👍

**Comment by pradeepmurugesan** [comment] 2019-10-07 15:38
@herflis Thanks.  I was able to repro the issue locally.. I would like to get a better understanding of the following statement in the expected behaviour, 
> If it is possible in this cases the current parent should be replaced with the deleted items parent

How do I decide the above ? Is there any parameters that already exists or should I make a decision based on something else. If its based on other params, can you kindly shed some light there.

**Comment by B3zo0** [comment] 2019-10-07 21:33
Hi Pradeep,

So what is happening here is that when you select an item in the tree it becomes the current parent. The bug seems to be that when we delete the current parent it tries to reload the deleted item.

I would try to change the current parent first when a content is deleted. As far as I know the current parent is taken from the url.

**Comment by pradeepmurugesan** [comment] 2019-10-08 07:45
I think I am lost here. Let's take the following tree and understand the scenario
```
Content
    |
    |
    |
    Sales WorkSpace
        |
        |
        Folder1
            |
            |
            Folder2
                |
                |
                File1.Txt
            
```

1. What happens when we delete `Folder2` ? 
       Will the `File1.Txt` be moved under Folder 1 ?  If Yes how do we decide the same ?
2. What happens when I delete `Folder1` ?

Kindly clarify @B3zo0 @herflis

**Comment by B3zo0** [comment] 2019-10-08 07:55
1. When you delete Folder2 the current parent should be Folder1 and File1.Txt will be deleted as well
2. Same here Sales Workspace should be the new current parent(content) and all of its children should be removed

**Comment by pradeepmurugesan** [comment] 2019-10-08 08:00
@B3zo0  Thanks for the clarification. This makes sense. 

Can you also tell me an example in the above tree for the case 2 mentioned in the description
> If the first solution cannot be made, then the delete action should not be displayed in the actionmenu in the tree.

In the above tree when shouldn't I render the `delete option` and also kindly elaborate the reason ?

**Comment by B3zo0** [comment] 2019-10-08 08:19
That is a possible fix for the bug. If you can not solve the parent content change somehow then it can also be a solution not to show a delete action on the current content in the tree.

**Comment by pradeepmurugesan** [comment] 2019-10-08 08:29
ah ok.. I understood it as a kind of `if else` for every node. Now got it. Thanks for the explanation

**Comment by pusztaienike** [comment] 2019-12-19 14:27
Dear @pradeepmurugesan :
Are you still working on this issue? If no: please assign it to me, or put it unassigned.
If so and need help: you can find all the neccessary information about contributing [here](https://github.com/SenseNet/sensenet/blob/master/CONTRIBUTING.md)
Thank you

**Closed** 2020-04-08 15:13 UTC
Labels: admin-ui, bug
