### ISSUE TITLE
[list-controls-react] Overwrite confirmation on name match

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#35] opened 2018-12-11 12:36 UTC
@kultsar commented on [Wed Aug 08 2018](https://github.com/SenseNet/sn-list-controls-react/issues/15)

If incremental naming is switched off, on uploading single or bulk files or directory uploads that contain items that would overwrite previously uploaded files or directories, the system should pop up a confirmation dialogue.
* After initiating the upload, the system should check target and source structure for matching path (dirs) or matching paths + filenames.
* Should stop at first match (in case of bulk files or dir upload), and ask for overwrite confirmation and for overwriting any other possible matches
* If user confirms, continue with upload and overwrite any matching items, otherwise cancel the upload

**Comment by tusmester** [comment] 2022-08-30 13:36
Duplicate of #387

**Closed by tusmester** 2022-08-30 13:36 UTC
Labels: list-controls-react
