### ISSUE TITLE
[E2E test] Add Cypress test - Drawer items navigation

### ISSUE THREAD

**Issue by taki9** [SenseNet/sn-client#745] opened 2020-07-21 13:12 UTC
# 🧪E2E test cases

The scope of these tests is to ensure that the drawer items link to the desired pages.

![drawer](https://user-images.githubusercontent.com/8918642/88055633-9b890000-cb5f-11ea-91aa-5186d42ad11e.PNG)

# 😎 Role

All test should run as **admin**.

# Test case 1

## 🧫 Purpose of the test
Click on the search (first from top in the picture) icon on the drawer should navigate to the Saved Queries page

## 🐾 Steps
1. Login with admin role
2. Click the search icon on the drawer

## Expected result
- browser navigated to the /saved-queries path

# Test case 2

## 🧫 Purpose of the test
Click on the  globe (second from top in the picture) icon on the drawer should navigate to the Content page

## 🐾 Steps
1. Login with admin role
2. Click the search icon on the drawer

## Expected result
- browser navigated to the /content/explorer path

# Test case 3

## 🧫 Purpose of the test
Click on the  people (third from top in the picture) icon on the drawer should navigate to the Users & Groups page

## 🐾 Steps
1. Login with admin role
2. Click the people icon on the drawer

## Expected result
- browser navigated to the /users-and-groups/explorer path

# Test case 4

## 🧫 Purpose of the test
Click on the  trash (fourth from top in the picture) icon on the drawer should navigate to the Trash page

## 🐾 Steps
1. Login with admin role
2. Click the trash icon on the drawer

## Expected result
- browser navigated to the /trash/explorer path

# Test case 5

## 🧫 Purpose of the test
Click on the  widgets (fifth from top in the picture) icon on the drawer should navigate to the Content Types page

## 🐾 Steps
1. Login with admin role
2. Click the widgets icon on the drawer

## Expected result
- browser navigated to the /content-types/explorer path

# Test case 6

## 🧫 Purpose of the test
Click on the language (sixth from top in the picture) icon on the drawer should navigate to the Content Types page

## 🐾 Steps
1. Login with admin role
2. Click the language icon on the drawer

## Expected result
- browser navigated to the /localization/explorer path

# Test case 7

## 🧫 Purpose of the test
Click on the build (seventh from top in the picture) icon on the drawer should navigate to the Setup page

## 🐾 Steps
1. Login with admin role
2. Click the build icon on the drawer

## Expected result
- browser navigated to the /setup path

**Comment by raihan71** [comment] 2020-10-13 09:04
hey, it looks like a more simple test, can you assign this to me?

**Comment by herflis** [comment] 2020-10-13 09:11
> hey, it looks like a more simple test, can you assign this to me?

@raihan71 ok, it's yours now :) Let us know if we can help you!

**Comment by raihan71** [comment] 2020-10-13 09:18
> > hey, it looks like a more simple test, can you assign this to me?
> 
> @raihan71 ok, it's yours now :) Let us know if we can help you!

thanks, I just want to know step by step how to start? can u break it down here?

**Comment by herflis** [comment] 2020-10-13 09:23
> > > hey, it looks like a more simple test, can you assign this to me?
> > 
> > 
> > @raihan71 ok, it's yours now :) Let us know if we can help you!
> 
> thanks, I just want to know step by step how to start? can u break it down here?

I suggest you first to look at the contribution guide [here](https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md) for the actual steps and help and then check the tests that have already been written [here](https://github.com/SenseNet/sn-client/tree/develop/apps/sensenet/cypress/integration/ui).

**Comment by raihan71** [comment] 2020-10-13 09:31
> > > > hey, it looks like a more simple test, can you assign this to me?
> > > 
> > > 
> > > @raihan71 ok, it's yours now :) Let us know if we can help you!
> > 
> > 
> > thanks, I just want to know step by step how to start? can u break it down here?
> 
> I suggest you first to look at the contribution guide [here](https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md) for the actual steps and help and then check the tests that have already been written [here](https://github.com/SenseNet/sn-client/tree/develop/apps/sensenet/cypress/integration/ui).

OK, big thanks I think I'll try it

**Comment by raihan71** [comment] 2020-10-13 09:35
![image](https://user-images.githubusercontent.com/31585789/95843388-d58a2c80-0d71-11eb-8e41-b0abb57ad494.png)

I was trying to run <code>yarn start:dms:e2e</code> got this, can help?

**Comment by herflis** [comment] 2020-10-13 09:41
> ![image](https://user-images.githubusercontent.com/31585789/95843388-d58a2c80-0d71-11eb-8e41-b0abb57ad494.png)
> 
> I was trying to run `yarn start:dms:e2e` got this, can help?

I think you're looking another contribution guide, check [this one](https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md) because the one you've started to follow is for the dms app, but now you are writing tests for the admin-ui app (/apps/sensenet)

[https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md](https://github.com/SenseNet/sn-client/blob/develop/apps/sensenet/cypress/CONTRIBUTING.md)

**Comment by raihan71** [comment] 2020-10-14 10:13
![image](https://user-images.githubusercontent.com/31585789/95975503-7515f080-0e40-11eb-84ad-78bd3673b6b3.png)

@herflis do you know what is going on here? I was trying to run the test

**Comment by herflis** [comment] 2020-10-14 10:47
@raihan71 have you try setting the urls and the secrets in the config (cypress.json) as it is stated in the contribution guide?

![image](https://user-images.githubusercontent.com/6968860/95979036-4fc2bb80-0e1b-11eb-81da-15ad84277db4.png)

**Comment by raihan71** [comment] 2020-10-14 10:52
> @raihan71 did you try setting the urls and the secrets in the config (cypress.json) as it is stated in the contribution guide?
> 
> ![image](https://user-images.githubusercontent.com/6968860/95979036-4fc2bb80-0e1b-11eb-81da-15ad84277db4.png)
> 

Yes already, do I need to run npm start?

**Comment by herflis** [comment] 2020-10-14 10:54
you have to be in the `/apps/sensenet` folder and then run `yarn cypress:all`

**Comment by herflis** [comment] 2020-10-14 10:55
or `npm run cypress:all`

**Comment by herflis** [comment] 2020-10-15 13:55
Hi @raihan71 have you managed to solve it? Can we help you with something? :)

**Comment by raihan71** [comment] 2020-10-16 05:31
> Hi @raihan71 have you managed to solve it? Can we help you with something? :)

hi there, I've solved it and I can run npm cypress now, but I don't know how to start to write some tests without seeing the feature first by clicking through the browser

**Comment by herflis** [comment] 2020-10-16 06:32
Hi @raihan71 you can use the your repository you've requested to check the feature :) Login to your profile at [profile.sensenet.com](https://profile.sensenet.com/?redirectToLogin) and open your repository. It will take you to the admin ui where you can try the related things.

**Comment by raihan71** [comment] 2020-10-20 06:23
> Hi @raihan71 you can use the your repository you've requested to check the feature :) Login to your profile at [profile.sensenet.com](https://profile.sensenet.com/?redirectToLogin) and open your repository. It will take you to the admin ui where you can try the related things.

I'm so sorry I've been busy lately I cant finish it

**Comment by arc9693** [comment] 2020-10-22 08:47
@herflis I would like to take this up.

**Comment by herflis** [comment] 2020-10-22 08:52
Hi @arc9693 the issue is now assigned to you. Let us know if we can help you! :)

**Comment by arc9693** [comment] 2020-10-22 12:37
@herflis I have linked the PR. Can you please review it?

**Closed** 2020-10-27 16:48 UTC
Labels: cypress, good first issue, hacktoberfest, help wanted, test
